---
engines:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD001:
        enabled: false
      MD013:
        enabled: false
      MD024:
        enabled: false
      MD026:
        enabled: false
      MD033:
        enabled: false
      MD034:
        enabled: false
      MD036:
        enabled: false
ratings:
  paths:
  - "**/*.md"
exclude_paths: []
