---
engines:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
      MD024:
        enabled: false
      MD026:
        enabled: false
ratings:
  paths:
  - "**/*.md"
exclude_paths: []
